### ISSUE TITLE
Data viz with dials with issues

### ISSUE THREAD

**Issue by dani-lbnl** [nksauter/fv5080#7]
Unable to read data with dials - any suggestions on how to solve this issue? thx
**dials.image_viewer /Users/dani/Dropbox/data/r0027_2000.h5** 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Sorry: Unable to handle the following arguments:
  "/Users/dani/Dropbox/data/r0027_2000.h5" failed during ExperimentList processing:
    Traceback (most recent call last):
      File "/Applications/dials-v3-14-1/modules/dials/src/dials/util/options.py", line 321, in try_read_experiments
        data=ExperimentListFactory.from_json_file(
      File "/Applications/dials-v3-14-1/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 768, in from_json_file
        infile.read(), check_format=check_format, directory=directory
      File "/Applications/dials-v3-14-1/build/../conda_base/python.app/Contents/MacOS/../../../lib/python3.10/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by nksauter** [comment]
@dani-lbnl first thing would be to make sure that you've installed for format file described in step 3 of the README https://github.com/nksauter/fv5080/blob/master/README.md.  If that doesn't help you could schedule me for a Zoom call.
